AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the API EC2 instance. This assumes a default VPC present with public subnets.

Parameters:
  tagName:
    Type: String
    Description: The training session name such as bootcamp-feb-2018 or extended-paatshala-march-2018

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Join [ "-", [ "API-Box-SecurityGroup", Ref: tagName ] ]
      GroupDescription: Allows SSH and 9090 port access to the API box from the world.
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '9090'
        ToPort: '9090'
        CidrIp: 0.0.0.0/0

  ElasticIP:
    Type: "AWS::EC2::EIP"


Outputs:
 IPOfAPI:
   Description: Public IP of the API
   Value: !Ref ElasticIP
   Export:
     Name: !Join [ "-", [ "API-Box-IP", Ref: tagName ] ]

 SecurityGroupID:
    Description: SecurityGroupID
    Value: !Ref SecurityGroup
    Export:
      Name: !Join [ "-", [ "SecurityGroup-API", Ref: tagName ] ]