---
version: '2.1'
services:
  db:
    image: regsethu/bootcamp-postgres-dev:1.0.0
    ports:
      - "7654:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d spicinemas -U spiuser"]
      interval: 30s
      timeout: 30s
      retries: 3  
      
  spring-boot:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy  
    